// <auto-generated />
using System;
using math4ktu_be.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace math4ktu_be.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260421120000_UpdateEnumsAndRemoveCognitive")]
    partial class UpdateEnumsAndRemoveCognitive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("math4ktu_be.Data.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementArea")
                        .HasColumnType("int");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionCategoryClass")
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentQuestionId");

                    b.ToTable("Questions");

                    b.HasDiscriminator<int>("QuestionType").HasValue(1).HasValue(2).HasValue(3).HasValue(4);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Student"
                        });
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentSessionId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.StudentTestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuestionIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TestAssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestAssignmentId");

                    b.ToTable("StudentTestSessions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.TestAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedClass")
                        .HasColumnType("int");

                    b.Property<string>("AssignedClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestAssignments");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.TestQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Points")
                        .HasColumnType("float");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestId", "QuestionId")
                        .IsUnique();

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.FillBlanksQuestion", b =>
                {
                    b.HasBaseType("math4ktu_be.Data.Models.Question");

                    b.Property<string>("TextWithBlanks")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("math4ktu_be.Data.Models.Question");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.OpenEndedQuestion", b =>
                {
                    b.HasBaseType("math4ktu_be.Data.Models.Question");

                    b.Property<int>("MaxCharsAllowed")
                        .HasColumnType("int");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("math4ktu_be.Data.Models.Question");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Question", b =>
                {
                    b.HasOne("math4ktu_be.Data.Models.Question", "ParentQuestion")
                        .WithMany("SubQuestions")
                        .HasForeignKey("ParentQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentQuestion");

                    b.Navigation("SubQuestions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.StudentAnswer", b =>
                {
                    b.HasOne("math4ktu_be.Data.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("math4ktu_be.Data.Models.StudentTestSession", null)
                        .WithMany("StudentAnswers")
                        .HasForeignKey("StudentSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.StudentTestSession", b =>
                {
                    b.HasOne("math4ktu_be.Data.Models.Student", null)
                        .WithMany("StudentTestSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("math4ktu_be.Data.Models.TestAssignment", null)
                        .WithMany("StudentTestSessions")
                        .HasForeignKey("TestAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.TestAssignment", b =>
                {
                    b.HasOne("math4ktu_be.Data.Models.Test", null)
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.TestQuestion", b =>
                {
                    b.HasOne("math4ktu_be.Data.Models.Question", "Question")
                        .WithMany("TestQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("math4ktu_be.Data.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Student", b =>
                {
                    b.Navigation("StudentTestSessions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.Question", b =>
                {
                    b.Navigation("SubQuestions");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.TestAssignment", b =>
                {
                    b.Navigation("StudentTestSessions");
                });

            modelBuilder.Entity("math4ktu_be.Data.Models.StudentTestSession", b =>
                {
                    b.Navigation("StudentAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
